services:
  postgres:
    image: postgres:17
    container_name: devcollab-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: devcollab
      POSTGRES_PASSWORD: devcollab_123
      POSTGRES_DB: devcollab

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: